import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "FitLand",
  description: "Generated by create next app",
  icons: "/favicon.png",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-MorabbaLight overflow-auto"
      >
        {children}
      </body>
    </html>
  );
}
